# This file specifies your Python application's runtime configuration
runtime: python27
threadsafe: true
api_version: 1

# Handlers tell App Engine how to route requests to your application.
handlers:
- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: static/index\.html

# This handler routes requests to your APIs to your Endpoints code.
- url: /_ah/spi/.*
#- url: /_ah/api/.*
  script: helloworld_api.APPLICATION

# Third party libraries that are included in the App Engine SDK must be listed
# TODO: List any other App Engine SDK libs you may need here.

libraries:
# The pycrypto library is used for OAuth 2, and is also a requirement for APIs that wish to authenticate users.
- name: pycrypto
  version: latest

- name: ssl
  version: latest

- name: endpoints
  version: 1.0
